### ISSUE TITLE
HTTPS support

### ISSUE THREAD

**Issue by Grawl** [posthtml/posthtml-img-autosize#14]
Looks like this plugin cannot download image through HTTPS

```
Protocol "https:" not supported. Expected "http:"
```

because of `http` https://github.com/posthtml/posthtml-img-autosize/commit/a9b2657e47b399426de6b28c03de8986bb6110d5#diff-07e863069b945fbbcf06fdd3cc158305R3

**Comment by Grawl** [comment]
fixed with dff7a9b650e01c34b79c15bec7320eaaca010041

**Comment by Grawl** [comment]
fix still not released on NPM

**Comment by maltsev** [comment]
Sorry for the delay! I'll release it in the next days.

**Comment by maltsev** [comment]
I released it as [0.1.5](https://github.com/posthtml/posthtml-img-autosize/releases/tag/0.1.5).
