### ISSUE TITLE
Cannot handle error from image-size package

### ISSUE THREAD

**Issue by Grawl** [posthtml/posthtml-img-autosize#16]
My script looks like this:

```js
try {
	const body = await posthtml()
		.use(require('posthtml-img-autosize')({
			processEmptySize: true,
		}))
		.process(html)
		.then(result => result.html)
		.catch(error => {
			console.log({ error })
		})
	return body
} catch (error) {
	console.log(error)
}
```

I have `try/catch` here and `.catch` in promise, what I am doing wrong?

But I have `TypeError: unsupported file type: undefined (file: undefined)` on one of my pages.

This image causes this error:

![1400593094_shiny](https://user-images.githubusercontent.com/846774/75892657-6bc1b000-5e7d-11ea-9180-946ac2bb7f50.jpg)

**Comment by maltsev** [comment]
The second `undefined` in that error message is the image file path:

```js
// node_modules/image-size/lib/index.js
throw new TypeError('unsupported file type: ' + type + ' (file: ' + filepath + ')');
```

So I assume that the lib just couldn't find the image. 

I also checked, your code works on my machine. I'm closing this ticket since it doesn't seem like a bug in `posthtml-img-autosize`. Feel free to re-open if needed.

**Comment by Grawl** [comment]
its broken image. I fix it using imgproxy
